### ISSUE TITLE
[DISCUSS] Release Plan of ShardingSphere on Cloud 0.1.1

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere-on-cloud#131]
## Release 0.1.1

Hi community,

After last release, we have received a lot of feedback from users and developers. Now we plan to release the ShardingSphere on Cloud 0.2.0 version these days, which has made a lot of optimization and improvement for these feedback.

Please refer to this release notes to confirm whether it contains the features you expect. If I missed anything, please remind me ASAP. If there are any suggestions, please feel free to tell us.

### New Feature

1. Support using Terraform to deploy a ShardingSphere Proxy Cluster in  Multiple AZs

### Enhancement

1. Support using CloudFormation to deploy a ShardingSphere Proxy Cluster in  Multiple AZs
1. Add nameOverride parameter for helm charts, allowing users to override resource names

**Comment by TeslaCN** [comment]
This release is enhancement for 0.1.0, I'm changing the version to 0.1.1

**Comment by windghoul** [comment]
New Feature
2. Add nameOverride parameter for helm charts, allowing users to override resource names
