### ISSUE TITLE
question about helm start shardingsphere proxy，

### ISSUE THREAD

**Issue by lhjie** [apache/shardingsphere-on-cloud#158]
I`m use helm start shardingSphere proxy，by source code install，
now proxy started，but can not config rules in values.ymal ,
if I do it ,I`ll get  exception:
Cannot create property=rules for JavaBean=org.apache.shardingsphere.proxy.backend.config.yaml.YamlProxyDatabaseConfiguration@971s0s8 in 'reader',line 1 colum 1:
dataSources:
java.lang.InstantiationException
in 'reader', line 22,column 1:
 - shardingAlgorithms:

And I get the shardingsphere source code checked  the name is matched.Also compared the example config-sharding.yaml.
I can't find the cause of the problem.
so,anyone do it success,please teach me。
Repeat my question：
I want use helm start shardingSphere-proxy，and config the rules。 THX！

**Comment by xuanyuan300** [comment]
Hi ihjie， you need to using [ DISTSQL ](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-proxy/distsql/usage/) to add Sharding Rule.

**Comment by mlycore** [comment]
any updates on this ? @lhjie

**Comment by mlycore** [comment]
stale issues, will be closed
