### ISSUE TITLE
🐞 bug: no matches found: compute.serverConfig.authority.users[0].user (serverConfig user and password not applied in Helm properly)

### ISSUE THREAD

**Issue by windson** [apache/shardingsphere-on-cloud#183]
### Environment

Kubectl:

`
Client Version: v1.26.0
Kustomize Version: v4.5.7
`
Helm:
`version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.19.4"}`

I am using https://github.com/apache/shardingsphere-on-cloud/tree/main/charts/apache-shardingsphere-proxy-charts

- Contents of your values.yaml file,if your helm deployment process goes wrong.

No changes in values.yaml. Just overriding them via helm `--set` as mentioned below.

When I try the following, I see the error `zsh: no matches found: compute.serverConfig.authority.users[0].user=root`

```
helm upgrade --install hello-pp-chart shardingsphere/apache-shardingsphere-proxy-charts --version 0.1.0 --set compute.serverConfig.authority.users[0].user=root --set compute.serverConfig.authority.users[0].password=root
```

Alternatively, when I try the following, I see a warning `coalesce.go:223: warning: destination for apache-shardingsphere-proxy-charts.compute.serverConfig.authority.users is a table. Ignoring non-table value ([map[password:root user:root@%]])
coalesce.go:223: warning: destination for apache-shardingsphere-proxy-charts.compute.serverConfig.authority.users is a table. Ignoring non-table value ([map[password:root user:root@%]])
Release "hello-pp-chart" has been upgraded. Happy Helming!`

```
helm upgrade --install hello-pp-chart shardingsphere/apache-shardingsphere-proxy-charts --version 0.1.0 --set compute.serverConfig.authority.users.user=root --set compute.serverConfig.authority.users.password=root
```

- Contents of your CRD resource file. Include proxy.shardingsphere.apache.org/v1alpha1 and proxyconfig.shardingsphere.apache.org/v1alpha1

- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version

### Issue description

- Which phase is not functioning properly, is it the installation phase or the apply CRD phase ?
Not able to set user and password for serverConfig in ShardingSphere-Proxy. I am using https://github.com/apache/shardingsphere-on-cloud/tree/main/charts/apache-shardingsphere-proxy-charts

### Error log

- Including ShardingSphere-Proxy error log and ShardingSphere-Operator error log
zsh: no matches found: compute.serverConfig.authority.users[0].user=root

### Expected result

Shoud pick up user and password for serverConfig when `--set` via helm install or upgrade.

**Comment by windghoul** [comment]
thanks for feed back. i will check it out later.

**Comment by windghoul** [comment]
Hi @windson ,you can try this to set values:
```
helm install sstest apache-shardingsphere-proxy-charts -n ss  --set compute.serverConfig.authority.users="{user:root,password:root}"
```
The reason for the bug is because helm passing array values through --set

references: https://stackoverflow.com/questions/53846273/helm-passing-array-values-through-set
