### ISSUE TITLE
🚀 request help: Deployment.yaml of apache-shardingsphere-proxy-charts replacing the custom yamls files in conf directory

### ISSUE THREAD

**Issue by windson** [apache/shardingsphere-on-cloud#191]
### Request description

When I am deploying the [apache-shardingsphere-proxy-charts](https://github.com/apache/shardingsphere-on-cloud/tree/main/charts/apache-shardingsphere-proxy-charts) to EKS, it is overriding the contents of `/opt/shardingsphere-proxy/conf` directory.

The [deployment.yaml](https://github.com/apache/shardingsphere-on-cloud/blob/main/charts/apache-shardingsphere-proxy-charts/templates/deployment.yaml#L80) file is mounting that directory and somehow it is mounting it with default server.yaml file generated from the configuration in values.yaml.

Is there any way to retain the custom conf files that I have already packaged in the docker image that is being used to deploy?

### Environment

- your apache-shardingsphere-proxy-charts Version: Current (0.1.2)
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version

```
{
  "clientVersion": {
    "major": "1",
    "minor": "26",
    "gitVersion": "v1.26.0",
    "gitCommit": "b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d",
    "gitTreeState": "clean",
    "buildDate": "2022-12-08T19:51:43Z",
    "goVersion": "go1.19.4",
    "compiler": "gc",
    "platform": "darwin/arm64"
  },
  "kustomizeVersion": "v4.5.7"
}
```

**Comment by windghoul** [comment]
You can try to use subpath for additional file mounting, but we do not recommend this method, because our helm is only responsible for the official image

**Comment by mlycore** [comment]
Any updates on this ?

**Comment by mlycore** [comment]
This will be closed if no more updates on this issue.
