### ISSUE TITLE
🐞 bug: terrform for aws

### ISSUE THREAD

**Issue by zhuangyq008** [apache/shardingsphere-on-cloud#213]
### Environment

When I execute 'terraform plan' an error is output, the message 
`Error: no matching Route53Zone found
│ 
│   with module.zk.data.aws_route53_zone.zone,
│   on modules/zk/main.tf line 74, in data "aws_route53_zone" "zone":
│   74: data "aws_route53_zone" "zone" {
`
 is output

### Issue description

When I execute 'terraform plan' an error is output, the message 
`Error: no matching Route53Zone found
│ 
│   with module.zk.data.aws_route53_zone.zone,
│   on modules/zk/main.tf line 74, in data "aws_route53_zone" "zone":
│   74: data "aws_route53_zone" "zone" {
`
 is output

### Error log

- Including ShardingSphere-Proxy error log and ShardingSphere-Operator error log
`Error: no matching Route53Zone found
│ 
│   with module.zk.data.aws_route53_zone.zone,
│   on modules/zk/main.tf line 74, in data "aws_route53_zone" "zone":
│   74: data "aws_route53_zone" "zone" {
`

### Expected result

The resource can be created successfully

**Comment by zhuangyq008** [comment]
The name of the hosted private zone.The AWS private 'hosted_zone' must be created first, and the private zone is associated with the VPC, so the variable 'vpcid' must be matched to find the matching 'route53_hosted_zone'

**Comment by xuanyuan300** [comment]
> The name of the hosted private zone.The AWS private 'hosted_zone' must be created first, and the private zone is associated with the VPC, so the variable 'vpcid' must be matched to find the matching 'route53_hosted_zone'

Thanks feedback, you are right. Is terraform executed successfully?, we will add this to document.

**Comment by zhuangyq008** [comment]
Yes, it do work! 发自我的 iPhone在 2023年2月20日，16:09，pierce ***@***.***> 写道：﻿

The name of the hosted private zone.The AWS private 'hosted_zone' must be created first, and the private zone is associated with the VPC, so the variable 'vpcid' must be matched to find the matching 'route53_hosted_zone'

Thanks feedback, you are right. Is terraform executed successfully?, we will add this to document.

**Comment by mlycore** [comment]
Thanks @zhuangyq008 , and please let us know if there is further problems.

**Comment by mlycore** [comment]
This will be closed due to stale issue
