### ISSUE TITLE
🚀 request help: Update Helm charts of ShardingSphere Proxy to support metrics agent.

### ISSUE THREAD

**Issue by mlycore** [apache/shardingsphere-on-cloud#241]
### Request description

Currently there is no metrics agent in ShardingSphere Proxy's Docker image which makes it somewhat difficult to spin up a ShardingSphere Proxy cluster with observability.

Community would package the agent after each release. So we may need to download this jar to the right path of the volume, rendering and mounting the needed config file and finally update start.sh script.

Here's some links may help:

- https://www.apache.org/dyn/closer.lua/shardingsphere/5.3.1/apache-shardingsphere-5.3.1-shardingsphere-agent-bin.tar.gz
- https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/observability/

### Environment

Any kubernetes cluster.

**Comment by moomman** [comment]
ky

**Comment by Xu-Wentao** [comment]
> ### Request description
> Currently there is no metrics agent in ShardingSphere Proxy's Docker image which makes it somewhat difficult to spin up a ShardingSphere Proxy cluster with observability.
> 
> Community would package the agent after each release. So we may need to download this jar to the right path of the volume, rendering and mounting the needed config file and finally update start.sh script.
> 
> Here's some links may help:
> 
> * https://www.apache.org/dyn/closer.lua/shardingsphere/5.3.1/apache-shardingsphere-5.3.1-shardingsphere-agent-bin.tar.gz
> * https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/observability/
> 
> ### Environment
> Any kubernetes cluster.

update shardingsphere-bin-agent link: 
https://archive.apache.org/dist/shardingsphere/5.3.1/apache-shardingsphere-5.3.1-shardingsphere-agent-bin.tar.gz

**Comment by moomman** [comment]
Modify the shardingsphere-proxy-charts to fix the issue
1. values.yaml, add `agent.enabled` to control agent open ;`agentConfig` will convert to agent.yaml as conf/agent , which is  parsed in configmap
2. add a `initContainer` to download agent in the previous comment, and tar it  in ` /opt/shardingsphere-proxy/agent`,mount it to proxy container
3. add a `env` called `JAVA_TOOL_OPTIONS`,it refer to the agent.jar we need
