### ISSUE TITLE
🚀 request help: Update ComputeNode to support observability

### ISSUE THREAD

**Issue by mlycore** [apache/shardingsphere-on-cloud#250]
### Request description

At present, ComputeNode only handles a normal ShardingSphere proxy cluster without any observability. We hope to bring observability to ComputeNode and let users declare metrics, tracing and logging in ComputeNode.

This means the operator has to do three things as below:
1. Check if observability is enabled and all of the configs are correct
2. Add an init container to download shardingsphere-agent.jar from Apache repo
3. Render the ConfigMap which contains config file for the agent
4. Inject environment variables like JVM_OPTS to introduce the agent jar to start.sh
5. Update Volume and VolumeMount to include agent config

### Environment

- your ShardingSphere-Operator Version
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version

**Comment by Xu-Wentao** [comment]
ok

**Comment by mlycore** [comment]
FYI,  in `ComputeNode.Spec.Bootstrap`, the agent config has been introduced: 
https://github.com/apache/shardingsphere-on-cloud/blob/b03679ca61038ab2a1f8dd2bfe6b11b302a60b05/shardingsphere-operator/api/v1alpha1/compute_node_types.go#L234-L241
as 
https://github.com/apache/shardingsphere-on-cloud/blob/b03679ca61038ab2a1f8dd2bfe6b11b302a60b05/shardingsphere-operator/api/v1alpha1/compute_node_types.go#L182-L195.
