### ISSUE TITLE
Introduce general infra chaos to ShardingSphere

### ISSUE THREAD

**Issue by mlycore** [apache/shardingsphere-on-cloud#253]

**Comment by mlycore** [comment]
Tasks:
- [ ] Introduce some kinds of Pod chaos to a running ShardingSphere cluster, including zookeeper, and observe the cluster status. Submit a pr contains config yaml after the test please.
- [ ] Introduce some kinds of Network chaos to a running ShardingSphere cluster, including Zookeeper, and observe the cluster status. Submit a pr contains config yaml after the test please.

**Comment by moomman** [comment]
I want to try this issue out , please assign it me ,thanks

**Comment by mlycore** [comment]
Thanks @moomman !

**Comment by mlycore** [comment]
https://github.com/apache/shardingsphere-on-cloud/issues/32#issuecomment-1471355157

**Comment by mlycore** [comment]
This will be discussed in #290
