### ISSUE TITLE
Refactor: Agent tracing was wrapped twice

### ISSUE THREAD

**Issue by mlycore** [apache/shardingsphere-on-cloud#258]
Refers to https://github.com/apache/shardingsphere-on-cloud/blob/4ae5381ceff9a1da1df5232bdfb063f62462e1cd/shardingsphere-operator/api/v1alpha1/compute_node_types.go#L166-L180

There is no need to wrap PluginTracing and Tracing for twice. The two struct should be merged into one like below:

```go
 // PluginTracing defines the plugin for tracing 
 type PluginTracing struct { 
 	// +optional 
 	Jaeger JaegerTracing `json:"jaeger,omitempty" yaml:"Jaeger"` 
 	// +optional 
 	Zipkin ZipkinTracing `json:"zipkin,omitempty" yaml:"Zipkin"` 
 	// +optional 
 	SkyWalking SkyWalkingTracing `json:"skyWalking,omitempty" yaml:"SkyWalking"` 
 	// +optional 
 	OpenTelemetry OpenTelemetryTracing `json:"openTelemetry,omitempty" yaml:"OpenTelemetry"`
 } 

```

**Comment by mlycore** [comment]
https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-proxy/observability/

**Comment by Xu-Wentao** [comment]
PR https://github.com/apache/shardingsphere-on-cloud/pull/260
