### ISSUE TITLE
Consider moving Helm Charts of ShardingSphere to this repo.

### ISSUE THREAD

**Issue by mlycore** [apache/shardingsphere-on-cloud#29]
Consider moving Helm Charts of ShardingSphere to this repo. So we can better collect the solutions.

**Comment by mlycore** [comment]
Please assign this to me. I'll copy the Charts to this repo.

**Comment by terrymanu** [comment]
Great!

**Comment by mlycore** [comment]
The directory has been copied in this pull request: #41

**Comment by mlycore** [comment]
Next, I'm going to update Readme and other domain info in the CRDs.
- [ ] update readme
- [ ] fix domain info
