### ISSUE TITLE
Migrating licenses headers and domains in project to ASF

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere-on-cloud#35]
### Request description

Since the ShardingSphere on Cloud has been donated to Apache ShardingSphere, we need to update copyrights and domains in project. Includes:
- [x] Update license headers to ASF. https://github.com/apache/shardingsphere-on-cloud/pull/34
- [ ] Update domains in project to `shardingsphere.apache.org`. Such as files:
   - https://github.com/apache/shardingsphere-on-cloud/blob/main/charts/shardingsphere-operator/crds/shardingsphere.sphere-ex.com_shardingsphereproxies.yaml
   - https://github.com/apache/shardingsphere-on-cloud/blob/eeb833a852f333cb88f1784b2dffb4b4656940ea/shardingsphere-operator/PROJECT#L1 

### Environment

None.

**Comment by windghoul** [comment]
refactor in #46
