### ISSUE TITLE
🐞 bug: PITR show backup records by csn , multiple backup csn records are the same, and only one record result is displayed.

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere-on-cloud#463]
### Environment

- Contents of your values.yaml file,if your helm deployment process goes wrong.
- Contents of your CRD resource file. Include proxy.shardingsphere.apache.org/v1alpha1 and proxyconfig.shardingsphere.apache.org/v1alpha1
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version

### Issue description

- Which phase is not functioning properly, is it the installation phase or the apply CRD phase ?
PITR show backup records by csn , multiple backup csn records are the same, and only one record result is displayed.

./gs_pitr show --csn "44698"

### Error log

- Including ShardingSphere-Proxy error log and ShardingSphere-Operator error log

### Expected result

PITR show backup records by csn , multiple backup csn records are the same, and all records can be showed

**Comment by mlycore** [comment]
In LocalStorage's ReadByCSN https://github.com/apache/shardingsphere-on-cloud/blob/3d87f11c573c94bd9f02c206238b94dfdf3adaf7/pitr/cli/internal/pkg/local-storage.go#L175-L186

We can see that the first backup record who match the requested CSN will be returned. And normally there should not have two or more backup records who shared identical CSN. 

This method could be kept and introduce another method `ReadAllByCSN()` to return all backup records containing the same CSN.
