### ISSUE TITLE
🐞 bug: There are multiple backup records with the same CSN in PITR, Only ID can be used for recovery

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere-on-cloud#476]
### Environment

- Contents of your values.yaml file,if your helm deployment process goes wrong.
- Contents of your CRD resource file. Include proxy.shardingsphere.apache.org/v1alpha1 and proxyconfig.shardingsphere.apache.org/v1alpha1
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version

### Issue description

- Which phase is not functioning properly, is it the installation phase or the apply CRD phase ?

There are multiple backup records with the same CSN in PITR, Only ID can be used for recovery

### Error log

- Including ShardingSphere-Proxy error log and ShardingSphere-Operator error log

**Comment by mlycore** [comment]
This is fixed in PR #467 . Generally there should not contain the same CSN in two different PITR backups. It sill add a way that user should using param `--backup-id`  if there are confusing CSNs as an exception handler.
