### ISSUE TITLE
🐞 bug: PITR's README.md should add the description that PITR backup record files are stored in the hidden folder，and how to restore when change host.

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere-on-cloud#477]
### Environment

- Contents of your values.yaml file,if your helm deployment process goes wrong.
- Contents of your CRD resource file. Include proxy.shardingsphere.apache.org/v1alpha1 and proxyconfig.shardingsphere.apache.org/v1alpha1
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version

### Issue description

- Which phase is not functioning properly, is it the installation phase or the apply CRD phase ?
PITR's README.md should add the description that PITR backup record files are stored in the hidden folder，and how to restore when change host

### Error log

- Including ShardingSphere-Proxy error log and ShardingSphere-Operator error log

**Comment by mlycore** [comment]
This is updated in PR #475. Refers: https://stackgres.io/doc/latest/reference/crd/sgshardedcluster/
