### ISSUE TITLE
🐞 bug: Each time PITR backup, the gs_probackup init operation is performed, and the agent reports an error.

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere-on-cloud#483]
### Environment

- Contents of your values.yaml file,if your helm deployment process goes wrong.
- Contents of your CRD resource file. Include proxy.shardingsphere.apache.org/v1alpha1 and proxyconfig.shardingsphere.apache.org/v1alpha1
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version

### Issue description

- Which phase is not functioning properly, is it the installation phase or the apply CRD phase ?
PITR

### Error log

- Including ShardingSphere-Proxy error log and ShardingSphere-Operator error log

{"level":"error","ts":"2023-12-26T10:36:03+08:00","caller":"pkg/opengauss.go:196","msg":"add instance failure[output=], err: exec failure[ee=exit status 1,stdout=ERROR: Instance 'ins-default-ss' backup directory already exists: '/home/peilq_og_sub/basebackup/backups/ins-default-ss'\n], wrap:10003-Command operate failed., wrap: 10006-The instance already exist."}

### Expected result

The gs_probackup init operation is performed for each PITR backup. The agent displays a message but does not report an error.

**Comment by mlycore** [comment]
`gs_probackup init` will be executed by pitr-agent before any backup progress starts. #480 And the backup data directory will also be created if not exist. #482
