### ISSUE TITLE
🚀 request help:  Dynamic suppport DataBase (etc, OpenGuass , MySQL , Oracle)

### ISSUE THREAD

**Issue by yu199195** [apache/shardingsphere-on-cloud#56]
### Request description

Dear Apache ShardingSphere Community,

Shardingsphere-on-cloud is a very good project to better deployment of ShardingSphere-Proxy.

Now maybe we need dynamic one-click deployment support for different types of databases, 

because ShardingSphere's SPI is designed to do just that.

Perhaps we can use this property to dynamic pulling of drivers.

`server.yaml` in ShardingSpere-Proxy

```yaml
proxy-frontend-database-protocol-type : OpenGuass  # MySQL , Oracle

```

Looking forward to seeing this feature~

### Environment

- your ShardingSphere-Operator Version
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version

**Comment by windghoul** [comment]
openGauss JDBC connect has been placed in the ShardingSphere-Proxy image with the source code by default
