### ISSUE TITLE
Add more cases for UpdateService unit test

### ISSUE THREAD

**Issue by mlycore** [apache/shardingsphere-on-cloud#80]
Hi community,

This issue is for #73 

Aim
---
Add more cases for UpdateService to improve unit test coverage.

Basic Qualifications
---

- [Golang Unit Test](golang.org)
- [stretchr/testify/assert](github.com/stretchr/testify/assert)
- [Kubernetes Deployment](kubernetes.io)

**Comment by amarps** [comment]
can you assign me? i would love to work on this issue.

**Comment by mlycore** [comment]
> can you assign me? i would love to work on this issue.

Of course, assigned and thanks ~
